Server_Name: "DEV01"

Whitelist:
  Enabled: true
  Block_Message: '&c&lYou are not whitelisted on this server!'
  Whitelisted_Ranks:
    - 'Admin'

Tablist:
  Header: "\\u+4E5E\\u+F801\\u+4EA1\n\n\n\n"
  Footer: "\n&#3A86FF ʙᴜʏ ʀᴀɴᴋs ᴀᴛ &#FFBE0Bsᴛᴏʀᴇ.ᴅᴇᴘᴛʜsᴄᴀᴘᴇ.ɴᴇᴛ \n"

Web_Socket:
  Server: true
  Host: "localhost"
  Port: 8080