name: Core
version: '${project.version}'
main: net.depthscape.core.CorePlugin
api-version: '1.20'
depend:
  - TAB
softdepend:
  - TAB
commands:
  corereload:
  createworld:
  staffchat:
    aliases:
      - sc
  vanish:
    aliases:
      - v
  test:
  noclip: