name: Core
version: '${project.version}'
main: net.depthscape.core.CorePlugin
api-version: '1.20'
depend:
  - TAB
  - ProtocolLib
softdepend:
  - TAB
commands:
  corereload:
  createworld:
  staffchat:
    aliases: [sc]
  vanish:
    aliases: [v]
  test:
  noclip:
  websocketrestart:
  dailyrestart:
  profile:
  punish:
  gmc:
  gms:
  gma:
  gmsp:
  gamemode:
    aliases: [gm]