name: Core
version: '${project.version}'
main: net.depthscape.core.CorePlugin
api-version: '1.20'
commands:
  corereload:
  createworld:
  staffchat:
    aliases:
      - sc
  vanish:
    aliases:
      - v
  dikkelul: